apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: acc-api
  name: acc-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: acc-api
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: acc-api
    spec:
      containers:
      - args:
        - serve
        env:
        - name: ACC_API_PORT
          value: "8080"
        image: f5devcentral/f5-automation-config-converter
        imagePullPolicy: "Always"
        name: acc-api
        ports:
        - containerPort: 8080
          hostIP: 127.0.0.1
        resources: {}
        volumeMounts:
        - mountPath: /tmp
          name: acc-api-tmpfs0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - emptyDir:
          medium: Memory
        name: acc-api-tmpfs0
status: {}
