apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: acc-api
  name: acc-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: acc-api
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: acc-api
    spec:
      containers:
        - args:
            - serve
          env:
            - name: ACC_API_PORT
              value: "8080"
          image: f5devcentral/f5-automation-config-converter:1.20.0
          name: acc-api
          resources: {}
          volumeMounts:
            - mountPath: /tmp
              name: acc-api-tmpfs0
      restartPolicy: Always
      volumes:
        - emptyDir:
            medium: Memory
          name: acc-api-tmpfs0
status: {}
