apiVersion: v1
kind: PersistentVolume
metadata:
  name: journeys-pv
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /kubefilesystem/appfiles/journeys
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: celery-pv
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /kubefilesystem/appfiles/journeys-celery
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /kubefilesystem/appfiles/journeys-postgres
