apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: journeys
  name: journeys
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: journeys
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: journeys
    spec:
#      volumes:
#      - name: local-storage
#        persistentVolumeClaim:
#          claimName: local-hostpath-pvc
      containers:
        - args:
            - runserver
          env:
          - name: ACC_API_HOST
            value: acc-api
          - name: ACC_API_PORT
            value: "8080"
          - name: BROKER_URL
            value: redis://redis:6379/0
          - name: DB_HOST
            value: postgres
          - name: DB_NAME
            value: postgres
          - name: DB_PASS
            value: postgres
          - name: DB_PORT
            value: "5432"
          - name: DB_USER
            value: postgres
          - name: JOURNEYS_PORT
            value: "8443"
          - name: MIGRATE_DIR
            value: /migrate
          image: f5devcentral/f5-bigip-journeys-app
          imagePullPolicy: "Always"
          name: journeys
          ports:
            - containerPort: 443
#              hostIP: 127.0.0.1
#          volumeMounts:
#          - mountPath: /mnt/store
#            name: local-storage
          resources: {}
      restartPolicy: Always
status: {}
